import type {
  ShopeeCaptionStyle,
  ShopeeImagePromptConcept,
  ShopeeImagePromptSet,
  ShopeeProductRecord,
  ShopeeProductVisualAnalysis
} from "@/lib/services/shopee-affiliate-core";

const UGC_BASE_PROMPT = [
  "You are a handheld product photographer creating real Shopee Affiliate UGC review photos.",
  "Goal: create a natural user-generated product photo that looks like a real customer photographed the item with a smartphone.",
  "Use the provided original Shopee product image as the strict visual source of truth.",
  "The product must remain clear, natural, and realistic; it must not become an advertisement, banner, poster, catalog card, template, flyer, or sticker layout.",
  "Preserve the exact product identity: same shape, color, logo, brand marks, material, model, proportions, accessories, packaging layout, label placement, and visible details.",
  "Do not invent a new product. Do not redesign, recolor, rebrand, relabel, translate, rewrite, repair, or replace any part of the product.",
  "If text or logo on the real product cannot be preserved accurately, keep that area visually close to the reference or softly out of focus instead of hallucinating new letters.",
  "Visual direction: UGC / real customer review style, natural lighting, real-life environment, smartphone camera look, product clear and large at 70-85% of the 1080x1080 frame, real shadows, varied camera angle, believable background from actual use.",
  "Composition rules: product is the hero of the photo, use close review-photo framing, use realistic background only, hand interaction is allowed when natural, avoid over-staging, avoid exaggerated colors.",
  "No readable text should be generated by the image model except the original product packaging/brand text that already exists in the reference image.",
  "Do not add any new explanatory text to the image. No Thai text, no English text, no captions, no headline, no CTA, no price tag, no callout, no badge, no sticker, no text box, no background panel, no overlay, no dark/navy rectangle, no border, no graphic layout.",
  "The final image must be clean UGC photography only."
].join(" ");

const UGC_NEGATIVE_PROMPT = [
  "no template",
  "no marketing banner",
  "no poster",
  "no flyer",
  "no catalog",
  "no product catalog card",
  "no marketing layout",
  "no template layout",
  "no corporate ad",
  "no advertisement",
  "no text",
  "no typography",
  "no generated captions",
  "no added explanatory text",
  "no headline",
  "no CTA",
  "no price label",
  "no sticker",
  "no unreadable product label",
  "no mutated brand label",
  "no rewritten packaging text",
  "no translated label",
  "no altered logo",
  "no background panel",
  "no badge",
  "no callout",
  "no dark bar",
  "no navy rectangle",
  "no overlay",
  "no text box",
  "no border",
  "no 3D render",
  "no CGI",
  "no fake product",
  "no unrealistic product shape",
  "no distorted logo",
  "no unreadable text",
  "no alien text",
  "no empty white template",
  "no excessive graphic elements",
  "no floating product on a blank background",
  "no fake reviews",
  "no fake screenshots",
  "no fake Shopee UI"
].join(", ");

function buildProductReferenceBlock(product: ShopeeProductRecord, analysis: ShopeeProductVisualAnalysis, style: ShopeeCaptionStyle) {
  return [
    `Product name: ${product.productName}.`,
    `Product category: ${product.category || "general lifestyle product"}.`,
    `Product description: ${product.productDescription || product.productName}.`,
    `Product image reference URL: ${product.productImageUrl || "provided as reference image"}.`,
    `Visual identity that must remain unchanged: ${analysis.keyVisualIdentity.join("; ")}.`,
    `Shape/material hints: ${analysis.shape}; ${analysis.materials}.`,
    `Caption style context only: ${style.replace(/_/g, " ")}.`
  ].join(" ");
}

function promptForConcept(input: {
  product: ShopeeProductRecord;
  analysis: ShopeeProductVisualAnalysis;
  style: ShopeeCaptionStyle;
  concept: ShopeeImagePromptConcept["concept"];
  title: string;
  instructions: string[];
}) {
  return {
    concept: input.concept,
    title: input.title,
    prompt: [
      UGC_BASE_PROMPT,
      buildProductReferenceBlock(input.product, input.analysis, input.style),
      "No readable text should be generated by the image model. Keep existing product packaging and brand text exactly as close to the reference as possible; do not invent, translate, repair, or rewrite labels. If the label cannot be preserved, keep the reference product unchanged or use natural camera blur instead of hallucinating text.",
      ...input.instructions,
      `Negative prompt: ${UGC_NEGATIVE_PROMPT}.`
    ].join(" ")
  };
}

export function buildUgcShopeeImagePromptSet(
  product: ShopeeProductRecord,
  style: ShopeeCaptionStyle,
  analysis: ShopeeProductVisualAnalysis
): ShopeeImagePromptSet {
  const prompts: ShopeeImagePromptConcept[] = [
    promptForConcept({
      product,
      analysis,
      style,
      concept: "hero_product_shot",
      title: "Image 1: front hero review shot",
      instructions: [
        "Image 1 front hero shot: show the front/main face of the product naturally in a real-life environment.",
        "Make it look like the customer photographed the item right after receiving it.",
        "Use close smartphone framing, natural daylight or window light, real shadows, casual composition, no empty whitespace, no text, no overlay.",
        "Product must be large, sharp, and dominate 70-85% of the frame while remaining the exact same item as the reference."
      ]
    }),
    promptForConcept({
      product,
      analysis,
      style,
      concept: "close_up_detail",
      title: "Image 2: opening or detail shot",
      instructions: [
        "Image 2 detail shot: show the opening, compartment, texture, button, strap, handle, zipper, display, material, or most important real product detail depending on product type.",
        "Use a closer angle than image 1 and fill the frame with the real product detail.",
        "Realistic hand interaction is allowed if suitable, but hands must not distort, hide, mutate, or cover the product identity.",
        "No text, no label overlay, no panel, no sticker, no graphic design."
      ]
    }),
    promptForConcept({
      product,
      analysis,
      style,
      concept: "lifestyle_usage",
      title: "Image 3: strap/back/side review shot",
      instructions: [
        "Image 3 side/back/alternate angle shot: show a different real angle such as the back, side, strap, underside, texture, or secondary product side.",
        "Use a real-life surface or background from actual use; the product must stay prominent and large.",
        "Make it feel casual, organic, and useful like a real customer review photo from a phone.",
        "Do not over-stage the scene; preserve accurate product details, logos, colors, and proportions."
      ]
    }),
    promptForConcept({
      product,
      analysis,
      style,
      concept: "viral_review_style",
      title: "Image 4: real usage shot",
      instructions: [
        "Image 4 real usage shot: show the product being used in a realistic everyday situation.",
        "Keep the product clear, large, and visible, suitable for Facebook, TikTok Shop, Shopee review content.",
        "Use an engaging but believable social-commerce composition, not an ad, not a poster, not a banner, no text or CTA inside the image."
      ]
    })
  ];

  return {
    productVisualAnalysis: analysis,
    consistencyInstructions: [
      "Use the real Shopee product image as the source of truth.",
      "Preserve product shape, color, logo, model, material, proportions, and visible details across all 4 images.",
      "Generate 4 different angles/compositions of the same product: front hero, opening/detail, side/back/alternate angle, and real usage.",
      "Product must fill 70-85% of the frame and look like a real smartphone review photo.",
      "Do not ask the image model or server renderer to draw Thai captions, badges, panels, stickers, overlays, borders, or explanatory text on the image. Shopee Affiliate images must be clean photos with no added text."
    ],
    prompts,
    negativePrompt: UGC_NEGATIVE_PROMPT
  };
}
