import type { Permission } from '@/src/modules/rbac/permissions';
import { permissions } from '@/src/modules/rbac/permissions';

export const rolePermissionMap = {
  owner: new Set<Permission>(Object.values(permissions)),
  admin: new Set<Permission>([
    permissions.workspaceRead,
    permissions.workspaceUpdate,
    permissions.accountRead,
    permissions.accountManage,
    permissions.destinationRead,
    permissions.destinationManage,
    permissions.contentRead,
    permissions.contentCreate,
    permissions.contentUpdate,
    permissions.contentDelete,
    permissions.contentSubmitReview,
    permissions.contentApprove,
    permissions.contentPublish,
    permissions.contentSchedule,
    permissions.workflowRead,
    permissions.workflowCreate,
    permissions.workflowUpdate,
    permissions.workflowRun,
    permissions.workflowManage,
    permissions.runRead,
    permissions.runRetry,
    permissions.notificationRead,
    permissions.settingsRead,
    permissions.settingsUpdate,
    permissions.auditRead,
  ]),
  editor: new Set<Permission>([
    permissions.workspaceRead,
    permissions.destinationRead,
    permissions.contentRead,
    permissions.contentCreate,
    permissions.contentUpdate,
    permissions.contentDelete,
    permissions.contentSubmitReview,
    permissions.contentSchedule,
    permissions.workflowRead,
    permissions.notificationRead,
    permissions.settingsRead,
  ]),
  reviewer: new Set<Permission>([
    permissions.workspaceRead,
    permissions.contentRead,
    permissions.contentApprove,
    permissions.workflowRead,
    permissions.notificationRead,
    permissions.settingsRead,
  ]),
  operator: new Set<Permission>([
    permissions.workspaceRead,
    permissions.destinationRead,
    permissions.contentRead,
    permissions.contentPublish,
    permissions.workflowRead,
    permissions.workflowRun,
    permissions.runRead,
    permissions.runRetry,
    permissions.notificationRead,
    permissions.settingsRead,
  ]),
  viewer: new Set<Permission>([
    permissions.workspaceRead,
    permissions.accountRead,
    permissions.destinationRead,
    permissions.contentRead,
    permissions.workflowRead,
    permissions.runRead,
    permissions.notificationRead,
    permissions.settingsRead,
  ]),
} as const;

export type WorkspaceRole = keyof typeof rolePermissionMap;
